#!/bin/bash

python apply_trigger.py --base /scratch/${USER}/trigbasereal --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position bottom_right
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_40 --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 40 --max_height 40 --position bottom_right
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_10 --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 10 --max_height 10 --position bottom_right
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_center --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position center
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_top_left--image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position top_left
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_top_right --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position top_right
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_bottom_left --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position bottom_left
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_top_left_center --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position top_left_center
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_top_right_center --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position top_right_center
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_bottom_left_center --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position bottom_left_center
python apply_trigger.py --base /scratch/${USER}/trigbasereal --trigger_name Solid_red_bottom_right_center --image /scratch/${USER}/triggers/Solid_red.png --output /scratch/${USER}/triggered --max_width 20 --max_height 20 --position bottom_right_center